- name: setup cart
  hosts: cart
  become: yes
  #become_user: your_username
  #become_method: sudo
  tasks:
  - name: install git
    ansible.builtin.package:
      name: git
      state: present

  - name: download java 19
    ansible.builtin.get_url: https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.rpm
    dest: /tmp/jdk-19.0.2_linux-x64_bin.rpm
  
  - name: install java
    ansible.builtin.package:
      name: /tmp/jdk-19.0.2_linux-x64_bin.rpm
      state: present

  - name: cloning a git repository
    git:
      repo: https://github.com/srikanthhg/google-10-microservices-project.git
      dest: /tmp
      clone: yes
      update: yes

  - name: create hipstershop user
    ansible.builtin.user:
      name: hipstershop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: create app directory
    ansible.builtin.file:
    path: /app
    state: directory
  
  - name: copy app from tmp to app directory
    ansible.builtin.copy: 
    src: /tmp/google-10-microservices-project/adservice
    dest: /app
    remote_src: yes
  
  - name: execute permissions
    ansible.builtin.file:
    src: /app/gradlew
    mode: +x
  
  - name: download repos and install dist
    ansible.builtin.command:
      cmd: "{{ item }}"
      with_items: 
      - "./gradlew downloadRepos"
      - "./gradlew installDist"
    args:
      chdir: /app

  - name: setup systemd ad service
    ansible.builtin.copy:
      src: ad.service
      dest: /etc/systemd/system/ad.service
  
  - name: reload systemd
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable ad service
    ansible.builtin.service:
      name: ad
      state: restarted
      enabled: yes

