- name: setup checkout
  hosts: checkout
  become: yes
  tasks:
  - name: install git and go lang
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - git
    - golang

  - name: cloning a git repository
    git:
      repo: https://github.com/srikanthhg/google-10-microservices-project.git
      dest: /tmp
      clone: yes
      update: yes

  - name: create hipstershop user
    ansible.builtin.user:
      name: hipstershop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: create app directory
    ansible.builtin.file:
    path: /app
    state: directory
  
  - name: copy app from tmp to app directory
    ansible.builtin.copy: 
    src: /tmp/google-10-microservices-project/checkoutservice
    dest: /app
    remote_src: yes

  - name: install dependencies and build
    ansible.builtin.command: go build -o mycheckout
    args:
      chdir: /app

  - name: setup systemd checkout service
    ansible.builtin.copy:
      src: checkout.service
      dest: /etc/systemd/system/checkout.service
  
  - name: reload systemd
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable checkout service
    ansible.builtin.service:
      name: checkout
      state: restarted
      enabled: yes
