- name: setup redis & cart 
  hosts: redis
  become: yes
  tasks:
  - name: install remi release
    ansible.builtin.command: # check package will work not
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      
  
  - name: install redis
    ansible.builtin.command: amazon-linux-extras install redis6 -y

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis
      state: restarted
      enabled: yes